// Code generated by api_gen. DO NOT EDIT.
// generated version: 2.1.0
package mock

import (
	"embed"
)

// MockJSONFS provides embed.FS for mock json
//go:embed json/*
var MockJSONFS embed.FS

// HeaderOption is the header of Api-Gen-Option in JSON
type HeaderOption struct {
	WaitMS          int64  `json:"wait_ms"`
	TargetFile      string `json:"target_file"`
	UseMatchRequest *bool  `json:"use_match_request"`
}
