// +build !mock

// Code generated by api_gen. DO NOT EDIT.
// generated version: 2.1.0
package server

import (
	"net/http"

	echo "github.com/labstack/echo/v4"
	types_interfaces_f6a158eb "github.com/star-integrations/project-boilerplate/back/interfaces"
	ctrl_controller_b6058628 "github.com/star-integrations/project-boilerplate/back/server/controller"
	apierror "github.com/star-integrations/project-boilerplate/back/server/pkg/apierror"
	props "github.com/star-integrations/project-boilerplate/back/server/props"
	xerrors "golang.org/x/xerrors"
)

func addRoutes(e *echo.Echo, p *props.ControllerProps) {
	add := func(method, path string, handler func(c echo.Context) (interface{}, error)) {
		e.Add(method, path, func(c echo.Context) error {
			var werr *apierror.APIError

			res, err := handler(c)

			if err != nil {
				if xerrors.As(err, &werr) {
					c.Logger().Errorf("%+v", werr)
					return c.JSON(werr.Status, werr.Body)
				}
				return err
			}
			if res == nil {
				return nil
			}

			return c.JSON(http.StatusOK, res)
		})
	}

	{
		ctrl := ctrl_controller_b6058628.NewGetHealthCheckController(p)

		add("GET", "/health_check", func(c echo.Context) (interface{}, error) {
			var werr *apierror.APIError

			req := new(types_interfaces_f6a158eb.GetHealthCheckRequest)
			if err := c.Bind(req); err != nil {
				c.Logger().Errorf("failed to bind a request for (/health_check): %+v", err)
				return nil, c.JSON(http.StatusBadRequest, map[string]interface{}{
					"code":    http.StatusBadRequest,
					"message": "invalid request.",
				})
			}
			if err := c.Validate(req); err != nil && err != echo.ErrValidatorNotRegistered {
				if xerrors.As(err, &werr) {
					return nil, c.JSON(werr.Status, werr.Body)
				}
				return nil, err
			}

			res, err := ctrl.GetHealthCheck(c, req)

			if err != nil {
				if xerrors.As(err, &werr) {
					return nil, c.JSON(werr.Status, werr.Body)
				}
				return nil, xerrors.Errorf("GetHealthCheck returned an error: %w", err)
			}

			if res == nil {
				return nil, nil
			}

			return res, nil
		})
	}

}
