runtime: nodejs14
service: default

handlers:
  - url: /_nuxt
    static_dir: dist/_nuxt
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt|svg))$
    static_files: dist/\1
    upload: dist/.*\.(gif|png|jpg|ico|txt|svg)$
    secure: always

  - url: /.*
    script: auto
    secure: always
