name: linter

on:
  pull_request:
    paths:
      - back/**
  push:
    branches:
      - main
      - develop
    paths:
      - back/**

jobs:
  api_gen:
    name: runner / gen_linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Set up bootstrap
        run: make bootstrap_firestore_repo bootstrap_mockgen

      - name: GoGenerate Check
        run: sh scripts/go-generate-checker.sh
